# Generated by Django 5.2.3 on 2025-06-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='title',
            field=models.CharField(default=models.CharField(max_length=50), max_length=100),
        ),
        migrations.AlterField(
            model_name='branch',
            name='logo',
            field=models.ImageField(default='branches/images/default_logo.png', upload_to='branches/images/'),
        ),
    ]
