# Generated by Django 5.2.3 on 2025-06-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_title_alter_branch_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='title',
            field=models.CharField(default='<django.db.models.fields.CharField>', max_length=100),
        ),
    ]
