# Generated by Django 5.2.3 on 2025-06-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_branch_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
